/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.wiquery.plugins.antilia.link;

/**
 *	
 * @author Ernesto Reinaldo Barreiro (reiern70@gmail.com)
 */
public enum JQIcon {
	
	ui_icon_carat_1_n,   
	ui_icon_carat_1_ne  ,   
	ui_icon_carat_1_e  ,   
	ui_icon_carat_1_se  ,   
	ui_icon_carat_1_s  ,   
	ui_icon_carat_1_sw  ,   
	ui_icon_carat_1_w  ,   
	ui_icon_carat_1_nw  ,   
	ui_icon_carat_2_n_s  ,  
	ui_icon_carat_2_e_w  ,   
	ui_icon_triangle_1_n  ,   
	ui_icon_triangle_1_ne  ,   
	ui_icon_triangle_1_e  ,   
	ui_icon_triangle_1_se  ,   
	ui_icon_triangle_1_s  ,   
	ui_icon_triangle_1_sw  ,   
	ui_icon_triangle_1_w  ,   
	ui_icon_triangle_1_nw  ,   
	ui_icon_triangle_2_n_s  ,  
	ui_icon_triangle_2_e_w  ,   
	ui_icon_arrow_1_n  ,   
	ui_icon_arrow_1_ne  ,   
	ui_icon_arrow_1_e  ,   
	ui_icon_arrow_1_se  ,   
	ui_icon_arrow_1_s  ,   
	ui_icon_arrow_1_sw  ,   
	ui_icon_arrow_1_w  ,   
	ui_icon_arrow_1_nw  ,   
	ui_icon_arrow_2_n_s  ,  
	ui_icon_arrow_2_ne_sw  ,   
	ui_icon_arrow_2_e_w  ,   
	ui_icon_arrow_2_se_nw  ,   
	ui_icon_arrowstop_1_n  ,   
	ui_icon_arrowstop_1_e  ,   
	ui_icon_arrowstop_1_s  ,   
	ui_icon_arrowstop_1_w  ,   
	ui_icon_arrowthick_1_n  ,   
	ui_icon_arrowthick_1_ne  ,   
	ui_icon_arrowthick_1_e  ,   
	ui_icon_arrowthick_1_se  ,   
	ui_icon_arrowthick_1_s  ,   
	ui_icon_arrowthick_1_sw  ,   
	ui_icon_arrowthick_1_w  ,   
	ui_icon_arrowthick_1_nw  ,   
	ui_icon_arrowthick_2_n_s  ,  
	ui_icon_arrowthick_2_ne_sw  ,   
	ui_icon_arrowthick_2_e_w  ,   
	ui_icon_arrowthick_2_se_nw  ,   
	ui_icon_arrowthickstop_1_n  ,   
	ui_icon_arrowthickstop_1_e  ,   
	ui_icon_arrowthickstop_1_s  ,   
	ui_icon_arrowthickstop_1_w  ,   
	ui_icon_arrowreturnthick_1_w  ,   
	ui_icon_arrowreturnthick_1_n  ,   
	ui_icon_arrowreturnthick_1_e  ,   
	ui_icon_arrowreturnthick_1_s  ,   
	ui_icon_arrowreturn_1_w  ,   
	ui_icon_arrowreturn_1_n  ,   
	ui_icon_arrowreturn_1_e  ,   
	ui_icon_arrowreturn_1_s  ,   
	ui_icon_arrowrefresh_1_w  ,  
	ui_icon_arrowrefresh_1_n  ,   
	ui_icon_arrowrefresh_1_e  ,   
	ui_icon_arrowrefresh_1_s  ,   
	ui_icon_arrow_4  ,   
	ui_icon_arrow_4_diag  ,   
	ui_icon_extlink  ,   
	ui_icon_newwin  ,   
	ui_icon_refresh  ,   
	ui_icon_shuffle  ,   
	ui_icon_transfer_e_w  ,   
	ui_icon_transferthick_e_w  ,   
	ui_icon_folder_collapsed  ,   
	ui_icon_folder_open  ,   
	ui_icon_document  ,   
	ui_icon_document_b  ,   
	ui_icon_note  ,   
	ui_icon_mail_closed  ,   
	ui_icon_mail_open  ,   
	ui_icon_suitcase  ,   
	ui_icon_comment  ,  
	ui_icon_person  ,   
	ui_icon_print  ,   
	ui_icon_trash  ,   
	ui_icon_locked  ,   
	ui_icon_unlocked  ,   
	ui_icon_bookmark  ,   
	ui_icon_tag  ,   
	ui_icon_home  ,   
	ui_icon_flag  ,   
	ui_icon_calendar,   
	ui_icon_cart  ,   
	ui_icon_pencil  ,   
	ui_icon_clock  ,   
	ui_icon_disk  ,   
	ui_icon_calculator  ,   
	ui_icon_zoomin  ,  
	ui_icon_zoomout  ,   
	ui_icon_search  ,   
	ui_icon_wrench  ,   
	ui_icon_gear  ,   
	ui_icon_heart  ,   
	ui_icon_star  ,   
	ui_icon_link  ,   
	ui_icon_cancel  ,  
	ui_icon_plus  ,  
	ui_icon_plusthick  ,  
	ui_icon_minus  ,  
	ui_icon_minusthick  ,  
	ui_icon_close  ,  
	ui_icon_closethick  ,  
	ui_icon_key  ,  
	ui_icon_lightbulb  , 
	ui_icon_scissors  ,  
	ui_icon_clipboard  ,  
	ui_icon_copy  ,  
	ui_icon_contact  ,  
	ui_icon_image  ,  
	ui_icon_video  ,  
	ui_icon_script  ,  
	ui_icon_alert  ,   
	ui_icon_info  ,   
	ui_icon_notice  ,   
	ui_icon_help  ,   
	ui_icon_check  ,   
	ui_icon_bullet  ,   
	ui_icon_radio_off  ,   
	ui_icon_radio_on  ,   
	ui_icon_pin_w  ,  
	ui_icon_pin_s  ,   
	ui_icon_play  ,   
	ui_icon_pause  ,   
	ui_icon_seek_next  ,   
	ui_icon_seek_prev  ,   
	ui_icon_seek_end  ,   
	ui_icon_seek_first  ,   
	ui_icon_stop  ,   
	ui_icon_eject  ,   
	ui_icon_volume_off  ,  
	ui_icon_volume_on  ,   
	ui_icon_power  ,   
	ui_icon_signal_diag  ,   
	ui_icon_signal  ,   
	ui_icon_battery_  ,   
	ui_icon_battery_1  ,   
	ui_icon_battery_2  ,   
	ui_icon_battery_3  ,   
	ui_icon_circle_plus  ,   
	ui_icon_circle_minus  ,   
	ui_icon_circle_close  ,   
	ui_icon_circle_triangle_e  ,   
	ui_icon_circle_triangle_s  ,   
	ui_icon_circle_triangle_w  ,   
	ui_icon_circle_triangle_n  ,   
	ui_icon_circle_arrow_e  ,   
	ui_icon_circle_arrow_s  ,  
	ui_icon_circle_arrow_w  ,   
	ui_icon_circle_arrow_n  ,   
	ui_icon_circle_zoomin  ,   
	ui_icon_circle_zoomout  ,   
	ui_icon_circle_check  ,   
	ui_icon_circlesmall_plus  ,   
	ui_icon_circlesmall_minus  ,   
	ui_icon_circlesmall_close  ,   
	ui_icon_squaresmall_plus  ,   
	ui_icon_squaresmall_minus  ,   
	ui_icon_squaresmall_close  ,   
	ui_icon_grip_dotted_vertical  ,   
	ui_icon_grip_dotted_horizontal  ,   
	ui_icon_grip_solid_vertical  ,   
	ui_icon_grip_solid_horizontal  ,   
	ui_icon_gripsmall_diagonal_se  ,   
	ui_icon_grip_diagonal_se;   
	
	public String getCssName() {
		return name().replace('_', '-');
	}
}
